# Generated by Django 5.2 on 2025-07-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('init', 'Init'), ('in_progress', 'Started'), ('finished', 'Finished')], default='init'),
        ),
    ]
