# Generated by Django 5.2 on 2025-07-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0008_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='position',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
