# Generated by Django 5.2 on 2025-09-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0017_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (None, 'unknown')], default=None, null=True),
        ),
    ]
